---@class Lime
Lime = Lime or {}
---@class Lime.Enum
Lime.Enum = Lime.Enum or {}
---@alias Lime.Enum.PrintColor integer
---@class Lime.Enum.PrintColorEnum
---@field White Lime.Enum.PrintColor
---@field Red Lime.Enum.PrintColor
---@field Green Lime.Enum.PrintColor
---@field Blue Lime.Enum.PrintColor
---@field Yellow Lime.Enum.PrintColor
Lime.Enum.PrintColor = {
White = 0,
Red = 1,
Green = 2,
Blue = 3,
Yellow = 4,
}
---@alias Lime.Enum.PopUpIcon integer
---@class Lime.Enum.PopUpIconEnum
---@field None Lime.Enum.PopUpIcon
---@field Warning Lime.Enum.PopUpIcon
---@field Message Lime.Enum.PopUpIcon
---@field Information Lime.Enum.PopUpIcon
Lime.Enum.PopUpIcon = {
None = 0,
Warning = 1,
Message = 2,
Information = 3,
}
---@alias Lime.Enum.DriverType integer
---@class Lime.Enum.DriverTypeEnum
---@field None Lime.Enum.DriverType
---@field Software Lime.Enum.DriverType
---@field SoftwarePlus Lime.Enum.DriverType
---@field Direct3D8 Lime.Enum.DriverType
---@field Direct3D9 Lime.Enum.DriverType
---@field OpenGL Lime.Enum.DriverType
Lime.Enum.DriverType = {
None = 0,
Software = 1,
SoftwarePlus = 2,
Direct3D8 = 3,
Direct3D9 = 4,
OpenGL = 5,
}
---@alias Lime.Enum.MaterialType integer
---@class Lime.Enum.MaterialTypeEnum
---@field Solid Lime.Enum.MaterialType
---@field SolidMultiplyLayers Lime.Enum.MaterialType
---@field Add Lime.Enum.MaterialType
---@field AlphaSoft Lime.Enum.MaterialType
---@field AlphaHarsh Lime.Enum.MaterialType
---@field SphereMap Lime.Enum.MaterialType
---@field ReflectMap Lime.Enum.MaterialType
Lime.Enum.MaterialType = {
Solid = 0,
SolidMultiplyLayers = 1,
Add = 12,
AlphaSoft = 13,
AlphaHarsh = 14,
SphereMap = 10,
ReflectMap = 11,
}
---@alias Lime.Enum.ImageWrapType integer
---@class Lime.Enum.ImageWrapTypeEnum
---@field Repeat Lime.Enum.ImageWrapType
---@field Clamp Lime.Enum.ImageWrapType
---@field ClampToEdge Lime.Enum.ImageWrapType
---@field Mirror Lime.Enum.ImageWrapType
---@field MirrorClamp Lime.Enum.ImageWrapType
---@field MirrorClampToEdge Lime.Enum.ImageWrapType
Lime.Enum.ImageWrapType = {
Repeat = 0,
Clamp = 1,
ClampToEdge = 2,
Mirror = 4,
MirrorClamp = 5,
MirrorClampToEdge = 6,
}
---@alias Lime.Enum.MaterialQuality integer
---@class Lime.Enum.MaterialQualityEnum
---@field Low Lime.Enum.MaterialQuality
---@field Medium Lime.Enum.MaterialQuality
---@field High Lime.Enum.MaterialQuality
Lime.Enum.MaterialQuality = {
Low = 0,
Medium = 1,
High = 2,
}
---@alias Lime.Enum.ImageCreationQuality integer
---@class Lime.Enum.ImageCreationQualityEnum
---@field Low Lime.Enum.ImageCreationQuality
---@field Medium Lime.Enum.ImageCreationQuality
---@field High Lime.Enum.ImageCreationQuality
Lime.Enum.ImageCreationQuality = {
Low = 0,
Medium = 1,
High = 2,
}
---@alias Lime.Enum.LightManagementType integer
---@class Lime.Enum.LightManagementTypeEnum
---@field EightNearest Lime.Enum.LightManagementType
---@field ThreeClosestToAll Lime.Enum.LightManagementType
---@field EmptyZones Lime.Enum.LightManagementType
Lime.Enum.LightManagementType = {
EightNearest = 0,
ThreeClosestToAll = 1,
EmptyZones = 2,
}
---@alias Lime.Enum.ZOrderMethod integer
---@class Lime.Enum.ZOrderMethodEnum
---@field BehindAll Lime.Enum.ZOrderMethod
---@field Default Lime.Enum.ZOrderMethod
---@field Decal Lime.Enum.ZOrderMethod
---@field ExceptDecal Lime.Enum.ZOrderMethod
---@field XRay Lime.Enum.ZOrderMethod
---@field StrictXRay Lime.Enum.ZOrderMethod
---@field OnTop Lime.Enum.ZOrderMethod
Lime.Enum.ZOrderMethod = {
BehindAll = 0,
Default = 1,
Decal = 2,
ExceptDecal = 3,
XRay = 4,
StrictXRay = 5,
OnTop = 6,
}
---@alias Lime.Enum.Mouse integer
---@class Lime.Enum.MouseEnum
---@field Left Lime.Enum.Mouse
---@field Right Lime.Enum.Mouse
---@field Middle Lime.Enum.Mouse
Lime.Enum.Mouse = {
Left = 0,
Right = 1,
Middle = 2,
}
---@alias Lime.Enum.ControllerButton integer
---@class Lime.Enum.ControllerButtonEnum
---@field A Lime.Enum.ControllerButton
---@field B Lime.Enum.ControllerButton
---@field X Lime.Enum.ControllerButton
---@field Y Lime.Enum.ControllerButton
---@field RightBumper Lime.Enum.ControllerButton
---@field LeftBumper Lime.Enum.ControllerButton
---@field Back Lime.Enum.ControllerButton
---@field Start Lime.Enum.ControllerButton
---@field RightStick Lime.Enum.ControllerButton
---@field LeftStick Lime.Enum.ControllerButton
---@field DPadUp Lime.Enum.ControllerButton
---@field DPadRight Lime.Enum.ControllerButton
---@field DPadDown Lime.Enum.ControllerButton
---@field DPadLeft Lime.Enum.ControllerButton
Lime.Enum.ControllerButton = {
A = 0,
B = 1,
X = 2,
Y = 3,
RightBumper = 4,
LeftBumper = 5,
Back = 6,
Start = 7,
RightStick = 8,
LeftStick = 9,
DPadUp = 32,
DPadRight = 33,
DPadDown = 34,
DPadLeft = 35,
}
---@alias Lime.Enum.ControllerAxis integer
---@class Lime.Enum.ControllerAxisEnum
---@field LeftStickX Lime.Enum.ControllerAxis
---@field LeftStickY Lime.Enum.ControllerAxis
---@field RightStickX Lime.Enum.ControllerAxis
---@field RightStickY Lime.Enum.ControllerAxis
---@field LeftTrigger Lime.Enum.ControllerAxis
---@field RightTrigger Lime.Enum.ControllerAxis
Lime.Enum.ControllerAxis = {
LeftStickX = 0,
LeftStickY = 1,
RightStickX = 3,
RightStickY = 4,
LeftTrigger = 5,
RightTrigger = 6,
}
---@alias Lime.Enum.Key integer
---@class Lime.Enum.KeyEnum
---@field Back Lime.Enum.Key
---@field Tab Lime.Enum.Key
---@field Return Lime.Enum.Key
---@field Shift Lime.Enum.Key
---@field Control Lime.Enum.Key
---@field Alt Lime.Enum.Key
---@field Pause Lime.Enum.Key
---@field CapsLock Lime.Enum.Key
---@field Escape Lime.Enum.Key
---@field Space Lime.Enum.Key
---@field PageUp Lime.Enum.Key
---@field PageDown Lime.Enum.Key
---@field End Lime.Enum.Key
---@field Home Lime.Enum.Key
---@field Left Lime.Enum.Key
---@field Up Lime.Enum.Key
---@field Right Lime.Enum.Key
---@field Down Lime.Enum.Key
---@field PrintScreen Lime.Enum.Key
---@field Insert Lime.Enum.Key
---@field Delete Lime.Enum.Key
---@field Num0 Lime.Enum.Key
---@field Num1 Lime.Enum.Key
---@field Num2 Lime.Enum.Key
---@field Num3 Lime.Enum.Key
---@field Num4 Lime.Enum.Key
---@field Num5 Lime.Enum.Key
---@field Num6 Lime.Enum.Key
---@field Num7 Lime.Enum.Key
---@field Num8 Lime.Enum.Key
---@field Num9 Lime.Enum.Key
---@field A Lime.Enum.Key
---@field B Lime.Enum.Key
---@field C Lime.Enum.Key
---@field D Lime.Enum.Key
---@field E Lime.Enum.Key
---@field F Lime.Enum.Key
---@field G Lime.Enum.Key
---@field H Lime.Enum.Key
---@field I Lime.Enum.Key
---@field J Lime.Enum.Key
---@field K Lime.Enum.Key
---@field L Lime.Enum.Key
---@field M Lime.Enum.Key
---@field N Lime.Enum.Key
---@field O Lime.Enum.Key
---@field P Lime.Enum.Key
---@field Q Lime.Enum.Key
---@field R Lime.Enum.Key
---@field S Lime.Enum.Key
---@field T Lime.Enum.Key
---@field U Lime.Enum.Key
---@field V Lime.Enum.Key
---@field W Lime.Enum.Key
---@field X Lime.Enum.Key
---@field Y Lime.Enum.Key
---@field Z Lime.Enum.Key
---@field LWin Lime.Enum.Key
---@field RWin Lime.Enum.Key
---@field Numpad0 Lime.Enum.Key
---@field Numpad1 Lime.Enum.Key
---@field Numpad2 Lime.Enum.Key
---@field Numpad3 Lime.Enum.Key
---@field Numpad4 Lime.Enum.Key
---@field Numpad5 Lime.Enum.Key
---@field Numpad6 Lime.Enum.Key
---@field Numpad7 Lime.Enum.Key
---@field Numpad8 Lime.Enum.Key
---@field Numpad9 Lime.Enum.Key
---@field NumpadMultiply Lime.Enum.Key
---@field NumpadAdd Lime.Enum.Key
---@field NumpadSeparator Lime.Enum.Key
---@field NumpadSubtract Lime.Enum.Key
---@field NumpadDecimal Lime.Enum.Key
---@field NumpadDivide Lime.Enum.Key
---@field F1 Lime.Enum.Key
---@field F2 Lime.Enum.Key
---@field F3 Lime.Enum.Key
---@field F4 Lime.Enum.Key
---@field F5 Lime.Enum.Key
---@field F6 Lime.Enum.Key
---@field F7 Lime.Enum.Key
---@field F8 Lime.Enum.Key
---@field F9 Lime.Enum.Key
---@field F10 Lime.Enum.Key
---@field F11 Lime.Enum.Key
---@field F12 Lime.Enum.Key
---@field NumLock Lime.Enum.Key
---@field ScrollLock Lime.Enum.Key
---@field LShift Lime.Enum.Key
---@field RShift Lime.Enum.Key
---@field LControl Lime.Enum.Key
---@field RControl Lime.Enum.Key
---@field LAlt Lime.Enum.Key
---@field RAlt Lime.Enum.Key
---@field Semicolon Lime.Enum.Key
---@field Equals Lime.Enum.Key
---@field Comma Lime.Enum.Key
---@field Minus Lime.Enum.Key
---@field Period Lime.Enum.Key
---@field Slash Lime.Enum.Key
---@field Backtick Lime.Enum.Key
---@field LeftBracket Lime.Enum.Key
---@field Backslash Lime.Enum.Key
---@field RightBracket Lime.Enum.Key
---@field Apostrophe Lime.Enum.Key
---@field Oem8 Lime.Enum.Key
---@field Oem102 Lime.Enum.Key
---@field OemClear Lime.Enum.Key
Lime.Enum.Key = {
Back = 8,
Tab = 9,
Return = 13,
Shift = 16,
Control = 17,
Alt = 18,
Pause = 19,
CapsLock = 20,
Escape = 27,
Space = 32,
PageUp = 33,
PageDown = 34,
End = 35,
Home = 36,
Left = 37,
Up = 38,
Right = 39,
Down = 40,
PrintScreen = 44,
Insert = 45,
Delete = 46,
Num0 = 48,
Num1 = 49,
Num2 = 50,
Num3 = 51,
Num4 = 52,
Num5 = 53,
Num6 = 54,
Num7 = 55,
Num8 = 56,
Num9 = 57,
A = 65,
B = 66,
C = 67,
D = 68,
E = 69,
F = 70,
G = 71,
H = 72,
I = 73,
J = 74,
K = 75,
L = 76,
M = 77,
N = 78,
O = 79,
P = 80,
Q = 81,
R = 82,
S = 83,
T = 84,
U = 85,
V = 86,
W = 87,
X = 88,
Y = 89,
Z = 90,
LWin = 91,
RWin = 92,
Numpad0 = 96,
Numpad1 = 97,
Numpad2 = 98,
Numpad3 = 99,
Numpad4 = 100,
Numpad5 = 101,
Numpad6 = 102,
Numpad7 = 103,
Numpad8 = 104,
Numpad9 = 105,
NumpadMultiply = 106,
NumpadAdd = 107,
NumpadSeparator = 108,
NumpadSubtract = 109,
NumpadDecimal = 110,
NumpadDivide = 111,
F1 = 112,
F2 = 113,
F3 = 114,
F4 = 115,
F5 = 116,
F6 = 117,
F7 = 118,
F8 = 119,
F9 = 120,
F10 = 121,
F11 = 122,
F12 = 123,
NumLock = 144,
ScrollLock = 145,
LShift = 160,
RShift = 161,
LControl = 162,
RControl = 163,
LAlt = 164,
RAlt = 165,
Semicolon = 186,
Equals = 187,
Comma = 188,
Minus = 189,
Period = 190,
Slash = 191,
Backtick = 192,
LeftBracket = 219,
Backslash = 220,
RightBracket = 221,
Apostrophe = 222,
Oem8 = 223,
Oem102 = 226,
OemClear = 254,
}